// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPwtPnPrG15bdu9YKpAAlQJuju1YkfNLM',
    appId: '1:284112301100:web:166be6f862fc27f5e93589',
    messagingSenderId: '284112301100',
    projectId: 'aaaa-2b41d',
    authDomain: 'aaaa-2b41d.firebaseapp.com',
    databaseURL: 'https://aaaa-2b41d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aaaa-2b41d.appspot.com',
    measurementId: 'G-2QGZJ8BBQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxAgDZRiUuyXpa3VBwRPubK7-uV8dztTQ',
    appId: '1:284112301100:android:fd75aa253beb6d46e93589',
    messagingSenderId: '284112301100',
    projectId: 'aaaa-2b41d',
    databaseURL: 'https://aaaa-2b41d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aaaa-2b41d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqDbG5IniWBVmObRjqsPsmaNAv5F9LGTs',
    appId: '1:284112301100:ios:4ced4789c198bd54e93589',
    messagingSenderId: '284112301100',
    projectId: 'aaaa-2b41d',
    databaseURL: 'https://aaaa-2b41d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aaaa-2b41d.appspot.com',
    iosClientId: '284112301100-9j2n99nhbl3k5ph11ekrdeap7hmrlcac.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqDbG5IniWBVmObRjqsPsmaNAv5F9LGTs',
    appId: '1:284112301100:ios:31af54b38bd67137e93589',
    messagingSenderId: '284112301100',
    projectId: 'aaaa-2b41d',
    databaseURL: 'https://aaaa-2b41d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aaaa-2b41d.appspot.com',
    iosClientId: '284112301100-hkc3ppb5m4kkh12ea1v104251g0dl6u9.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled3.RunnerTests',
  );
}
